stages:
  data_ingestion:
    cmd: python src/kidney_classification/pipeline/stage_01_data_ingestion.py
    deps:
      - src/kidney_classification/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone

  prepare_base_model:
    cmd: python src/kidney_classification/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/kidney_classification/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/kidney_classification/pipeline/stage_03_model_training.py
    deps:
      - src/kidney_classification/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/kidney_classification/pipeline/stage_04_model_evaluation_with_mlflow.py
    deps:
      - src/kidney_classification/pipeline/stage_04_model_evaluation_with_mlflow.py
      - config/config.yaml
      - artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
    metrics:
      - scores.json:
          cache: false
